spring:
  application:
    name: directory-server

  cloud:
    stream:
      function:
        definition: consumeStudyUpdate
      bindings:
        publishDirectoryUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}directory.update
        consumeStudyUpdate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
          group: directoryStudyUpdateGroup
      source: publishDirectoryUpdate

dbName: directory
