spring:
  application:
    name: directory-server

  cloud:
    function:
      definition: consumeStudyUpdate;consumeElementUpdate
    stream:
      bindings:
        publishDirectoryUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}directory.update
        consumeStudyUpdate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
          group: directoryStudyUpdateGroup
        consumeElementUpdate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}element.update
          group: directoryElementUpdateGroup
      output-bindings: publishDirectoryUpdate-out-0

powsybl-ws:
  database:
    name: directory

# Spring Boot + JVM auto-detects Kubernetes deployment environments. This checks happens at build time with Spring Native, so the
# liveness and readiness endpoints are not enabled automatically.
management:
  endpoint:
    health:
      probes:
        enabled: true