

server :
  port : 5026

spring:
  rabbitmq:
    addresses: localhost
  elasticsearch:
    uris:
      - http://localhost:9200
    connection-timeout: 60s
    socket-timeout: 60s
  ## to fill if authentication is needed
  # username:
  # password:

powsybl-ws:
  database:
    host: localhost

gridsuite:
  services:
    study-server:
      base-uri: http://localhost:5001
