

server :
  port : 5026

spring:
  rabbitmq:
    addresses: localhost
  elasticsearch:
    uris:
      - http://localhost:9200
  ## to fill if authentication is needed
  # username:
  # password:

powsybl-ws:
  database:
    host: localhost

gridsuite:
  services:
    -
      name: study-server
      base-uri: http://localhost:5001
    -
      name: user-admin-server
      base-uri: http://localhost:5033